theme = "hugo-theme-chunky-poster"
baseURL = "https://example.com"
copyright = "Copyright © 2020, Andrés Castro Socolich; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = "andresrcs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[languages]
  [languages.en]
    title = "Andres' Blog"
    description = "A place to showcase my personal,<br />data science related projects."
    weight = 0
    [languages.en.params]
      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "home"
          name = "Home"
          url = "/"
          weight = 1
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about/"
          weight = 0
  [languages.es]
    title = "El blog de Andrés"
    description = "Un lugar para mostrar mis proyectos<br/>personales relacionados con<br/>la ciencia de datos."
    weight = 1
    [languages.es.params]
      [languages.es.menu]
        [[languages.es.menu.main]]
          identifier = "home"
          name = "Inicio"
          url = "/"
          weight = 1
        [[languages.es.menu.main]]
          identifier = "about"
          name = "Acerca de"
          url = "/about/"
          weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[permalinks]
  post = "/:year/:month/:day/:slug/"
    
[params]
  author = "andres-castro"
  share = true
  showLanguageSwitcher = true
  homepageImage = "/images/homepage-image.jpg"

  [params.social]
    rss = true
    email = "andresrcs@outlook.com"
    facebook = "https://www.facebook.com/andresrcs"
    twitter = "https://twitter.com/Andresrcs"
    stack-overflow = "https://stackoverflow.com/users/5411245/andres"
    instagram = "https://www.instagram.com/asocolich/"
    github = "https://github.com/andresrcs"
    pinterest = "https://www.pinterest.com/andresrcs/"

  [params.prismJS]
    enable = true
    theme = "okaidia"

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
